version: '3.6'
services:
  app:
    build: .
    depends_on:
      - postgres-db
    container_name: vapor
    env_file:
      - app.env
  postgres-db:
    image: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    container_name: postgres-db
    ports:
      - "5432:5432"
    env_file:
      - app.env
volumes:
  pgdata:
    external: true



